
Reproducible Research, Project 1
================================

```{r, echo=FALSE}
library(ggplot2)
library(plyr)

activity <- read.csv("C://Users/Owner/datasciencecoursera/activity.csv")

activity$day <- weekdays(as.Date(activity$date))
activity$DateTime<- as.POSIXct(activity$date, format="%Y-%m-%d")
clean <- activity[!is.na(activity$steps),]

sumTable <- aggregate(activity$steps ~ activity$date, FUN=sum, )
colnames(sumTable)<- c("Date", "Steps")
```

##Histogram, total steps per day
```{r, echo=FALSE}
hist(sumTable$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day")
```

##Mean of Steps
```{r, echo=FALSE}
as.integer(mean(sumTable$Steps))
```

##Median of Steps
```{r, echo=FALSE}
as.integer(median(sumTable$Steps))
```


```{r, echo=FALSE}
##pulling data
library(plyr)
library(ggplot2)
clean <- activity[!is.na(activity$steps),]
intervalTable <- ddply(clean, .(interval), summarize, Avg = mean(steps))
```


```{r, echo=FALSE}
p <- ggplot(intervalTable, aes(x=interval, y=Avg), xlab = "Interval", ylab="Average Number of Steps")
p + geom_line()+xlab("Interval")+ylab("Average Number of Steps")+ggtitle("Average Number of Steps per Interval")
```

##Maximum steps by interval
```{r, echo=FALSE}
maxSteps <- max(intervalTable$Avg)
intervalTable[intervalTable$Avg==maxSteps,1]
```

##Total number of missing values ("NA")
```{r, echo=FALSE}
nrow(activity[is.na(activity$steps),])
```

```{r, echo=FALSE}
avgTable <- ddply(clean, .(interval, day), summarize, Avg = mean(steps))

nadata<- activity[is.na(activity$steps),]

newdata<-merge(nadata, avgTable, by=c("interval", "day"))

newdata2<- newdata[,c(6,4,1,2,5)]

colnames(newdata2)<- c("steps", "date", "interval", "day", "DateTime")

mergeData <- rbind(clean, newdata2)
```

##Mean of steps with NA data
```{r, echo=FALSE}
sumTable2 <- aggregate(mergeData$steps ~ mergeData$date, FUN=sum, )
colnames(sumTable2)<- c("Date", "Steps")
as.integer(mean(sumTable2$Steps))
```

##Median of steps with NA data
```{r, echo=FALSE}
as.integer(median(sumTable2$Steps))
```

##Histogram, total steps per day
```{r, echo=FALSE}
hist(sumTable2$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with NAs Fixed", col="Black")
hist(sumTable$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with NAs Fixed", col="Grey", add=T)
legend("topright", c("Imputed Data", "Non-NA Data"), fill=c("black", "grey") )
```


```{r, echo=FALSE}
mergeData$DayCategory <- ifelse(mergeData$day %in% c("Saturday", "Sunday"), "Weekend", "Weekday")
library(lattice) 
```

```{r, echo=FALSE}
intervalTable2 <- ddply(mergeData, .(interval, DayCategory), summarize, Avg = mean(steps))
```

##Panel plot
```{r, echo=FALSE}
xyplot(Avg~interval|DayCategory, data=intervalTable2, type="l",  layout = c(1,2),
       main="Average Steps per Interval Based on Type of Day", 
       ylab="Average Number of Steps", xlab="Interval")
```
